feat: allow background colour overrides for all breakpoints
comicrelief/component-library pull request #542
Opened 2023-01-16 15:47 UTC by pauldolden

#### What is it doing?

As per Jira: [ENG-2069]

#### Why is this required?
The theming work for the Donate widget requires the background colour to also show on SW.

#### link to Jira ticket:
Add a link to the Jira ticket.

### Quick Checklist:
- [ ] My PR title follows the Conventional Commit spec.

- [ ] I have filled out the PR description as per the template above.

- [ ] I have added tests to cover new or changed behaviour.

- [ ] I have updated any relevant documentation.

### Important! - lastly, make sure to squash merge...

[ENG-2069]: https://comicrelief.atlassian.net/browse/ENG-2069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-01-17 16:08 UTC, AndyEPhipps commented
![Screenshot 2023-01-17 at 16 07 29](https://user-images.githubusercontent.com/4737220/212951270-3541e70f-7ce8-442b-97f5-e76059d409a2.png)


Would be good to get bg colours added to these, and maybe put in a suitable 'using default transparent colour' example. I know it's a bit unwieldy with so many options, but good to have such things there to catch any weird bugs upd

2023-01-17 16:12 UTC, pauldolden commented
> ![Screenshot 2023-01-17 at 16 07 29](https://user-images.githubusercontent.com/4737220/212951270-3541e70f-7ce8-442b-97f5-e76059d409a2.png)
> 
> Would be good to get bg colours added to these, and maybe put in a suitable 'using default transparent colour' example. I know it's a bit unwieldy with so many options, but good to have such things there to catch any weird bugs upd

Cool. thanks Andy. I'll do that.

2023-01-17 16:13 UTC, AndyEPhipps commented
Given not about to use this in another context, I guess it does makes sense to do the 'theme' logic/mapping in the CRcom rather than here?

The only benefit doing it here would mean we could easily have a handful of working examples to see how all these options mesh; maybe it's just a case of making sure your CR PR env (and ultimately master_model) has a comprehensive demo page for this component to 'demo' them all?

2023-01-17 16:23 UTC, pauldolden commented
> Given we're not about to use this in _another_ context, I guess it does makes sense to do the 'theme' logic/mapping in the CRcom rather than here?
> 
> The only benefit doing it here would mean we could easily have a handful of working examples to see how all these options mesh; maybe it's just a case of making sure your CR PR env (and ultimately master_model) has a comprehensive demo page for this component to 'demo' them all? What do you reckon?

Yeah I was unsure about this myself, there is definitely some logic in the CR.com part of this PR, that I'm not a huge fan of, and does need a bit of refactoring, and it might be plausible to clean things up by doing it here. 

I think logic _should_ belong in CR.com, but I couldn't give you an iron clad reason why I believe that to be the case. One thing I do think might be a good compromise, would be to clean up the prop names a little to make it a bit clearer what things like `backgroundColor` actually mean.

2023-01-17 18:33 UTC, AndyEPhipps requested changes
Leaving an additional comment so GH gets off my back

2023-01-18 10:24 UTC, pauldolden commented
> Thinking... I suppose keeping it this way would mean all new 'theme' work for this could live purely within a CRcom PR, rather than having to do both? New 'theme' option added to the CMS, handled and mapped appropriately in the CRcom codebase, _badda-bing_.
> 
> Rather than over-engineer this component (when it should perhaps be a _bit_ 'dumb'), maybe we **are** best to keep the 'theme' definition and colour mapping within CRcom. If we _do_ ever end up using this component in another build, I'll do the legwork _and_ eat my hat

Yeah I think that's probably the right call. I'll get these quick changes made and hopefully get this merged, then finish off the CR.com stuff.

2023-01-18 15:07 UTC, AndyEPhipps approved these changes

2023-01-18 15:07 UTC, AndyEPhipps commented
💩

2023-01-18 15:09 UTC, merged