feat: RND23 Add Mr Men copy to footer on CR.com
comicrelief/component-library pull request #544
Opened 2023-01-20 13:51 UTC by michael-odonovan

### PR Titles
#### To pass testing pipeline, these need to follow Conventional Commits spec:
https://www.conventionalcommits.org/en/v1.0.0/
e.g.
`feat: create NewForm component`
or
`fix: update broken link in NewForm component`

### PR description
#### What is it doing?
Creates a reusable component for corporate sponsor logo or similar on every page, using our footer.

#### Why is this required?
RN23

#### link to Jira ticket:
https://comicrelief.atlassian.net/browse/ENG-2046

### Quick Checklist:
- [ ] My PR title follows the Conventional Commit spec.

- [ ] I have filled out the PR description as per the template above.

- [ ] I have added tests to cover new or changed behaviour.

- [ ] I have updated any relevant documentation.

### Important! - lastly, make sure to squash merge...

2023-01-20 15:54 UTC, pauldolden requested changes
Nice work, just a couple of little things I've noticed.

2023-01-20 15:54 UTC, pauldolden commented on src/components/Organisms/Footer/Footer.js
> +          <Text style={{ textAlign: 'left' }} align="left" tag="p" color="white">{additionalLegalLine}</Text>
Might be worth making this conditional, as currently the tag is showing appearing in the DOM but with no content:

```jsx
{additionalLegalLine && <Text style={{ textAlign: 'left' }} align="left" tag="p" color="white">{additionalLegalLine}</Text>}
          
```

```html
<p color="white" class="sc-gsTEea jZslOC"></p>
```

2023-01-20 15:54 UTC, pauldolden commented on src/components/Organisms/Footer/Footer.js
> +          <Text style={{ textAlign: 'left' }} align="left" tag="p" color="white">{additionalLegalLine}</Text>
Could add align to `Text` component.

2023-01-20 16:21 UTC, pauldolden commented on src/components/Organisms/Footer/Footer.js
> +          <Text style={{ textAlign: 'left' }} align="left" tag="p" color="white">{additionalLegalLine}</Text>
Infact ignore this.

2023-01-23 09:28 UTC, AndyEPhipps approved these changes

2023-01-23 09:47 UTC, pauldolden approved these changes
🚀

2023-01-23 09:47 UTC, merged