feat: donate button show amount
comicrelief/component-library pull request #557
Opened 2023-04-05 15:17 UTC by michael-odonovan

### PR description
#### What is it doing?
Adds the amount to be donated to the button when the moneybuys or custom amount are inputed / selected.

#### Why is this required?
FR / BBC around RND23

#### link to Jira ticket:
https://comicrelief.atlassian.net/browse/ENG-2353

### Quick Checklist:
- [x] My PR title follows the Conventional Commit spec.

- [x] I have filled out the PR description as per the template above.

- [x] I have added tests to cover new or changed behaviour.

- [x] I have updated any relevant documentation.

### Important! - lastly, make sure to squash merge...

2023-04-06 13:55 UTC, AndyEPhipps requested changes
Looks good to me, man- just two things:

While we're here, do you think we could update the button font to `inherit` the proper font-family?

Also, can you see what Curtis reckons of this? I feel like there's a nicer message to show here rather than just omitting the value:

![Screenshot 2023-04-06 at 14 52 14](https://user-images.githubusercontent.com/4737220/230398911-4d6f0288-de9e-458e-9af4-28e10183c76b.png)

2023-04-06 14:57 UTC, michael-odonovan commented
ok cool, will do

2023-04-19 12:49 UTC, michael-odonovan commented
- Curtis suggested that when the input field is left blank / cleared, the click outside should return the money buy to the default.
- I also removed the lonely "£" when no value is entered.

2023-04-19 15:00 UTC, AndyEPhipps commented on src/components/Organisms/Donate/Form/useClickOutside.js
> +  }, [amountRef, errorMsg]);
Can you add these useEffect deps in?

2023-04-19 15:04 UTC, AndyEPhipps commented on src/components/Organisms/Donate/Form/useClickOutside.js
> +    function handleClickOutside(event) {
Hmm could we move the function declaration out of the useEffect so we're not recreating  it unnecessarily each time?

2023-04-19 15:07 UTC, AndyEPhipps commented on src/components/Organisms/Donate/Form/useClickOutside.js
> +  }, [amountRef, errorMsg]);
Hmmm if you're binding the function to the mouseup and down functions, why does it need to be in a useEffect, retriggering when amountRef or errorMsg gets updated?

2023-04-19 15:08 UTC, AndyEPhipps commented on src/components/Organisms/Donate/Form/useClickOutside.js
> +      document.removeEventListener('mousedown', handleClickOutside);
V nice

2023-04-21 09:27 UTC, michael-odonovan commented
@AndyEPhipps 
Fiddled around with this a lot yesterday. 
- have moved the code back into the main Form.js file.
- the latest commit has the handleClickOutside function outside of the useEffect, however it will complain / error unless you wrap it in the useCallback hook.
- the previous commit has the handleClickOutside function inside the useEffect, and this obvs also works.
I'll leave it to you to decide which way to go.
I also added better button colours to the markdown examples as I couldn't see the red writing with the red background (this is on master as well).

2023-04-21 10:46 UTC, AndyEPhipps commented
Assigning Paul to review this too, so I'm not blocking it while I'm tied-up

2023-04-21 10:56 UTC, michael-odonovan commented
ok cool

2023-04-21 14:21 UTC, pauldolden commented
Everything seems to work here as expected here. Only question is about the snapshots, they appear to render the null values. Nothing that appears to affect the behaviour, but worth mentioning.

2023-04-21 14:29 UTC, michael-odonovan commented
> Only question is about the snapshots, they appear to render the null values. 

Cheers Paul. However I don't understand this bit. I can see src/components/Organisms/Donate/__snapshots__/Donate.test.js.snap, the jsx being changed by Jest/snapshots. But I don't understand null values?

2023-04-21 15:01 UTC, pauldolden commented
> > Only question is about the snapshots, they appear to render the null values.
> 
> Cheers Paul. However I don't understand this bit. I can see src/components/Organisms/Donate/**snapshots**/Donate.test.js.snap, the jsx being changed by Jest/snapshots. But I don't understand null values?

Hey Mike, apologies for the confusion here:
```
Donate £  now
```

I just meant that these are being rendered as per the above in the snapshots, just a comment more than anything else.

2023-04-21 15:10 UTC, michael-odonovan commented
oh yeah gotcha now => I suppose Jest can't parse the Js conditionals and just grabs from a state somewhere along the line?
I recon prob not worth messing with it as we just use snaps to check things haven't changed suddenly.
What you recon?

2023-04-25 08:46 UTC, michael-odonovan commented
Have changed null to 10 in the initial useState for the donation value, which has sorted this issue.

2023-04-25 09:37 UTC, pauldolden commented
> Have changed null to 10 in the initial useState for the donation value, which has sorted this issue.

Cool, I'm happy to approve this. All seems to work as expected. Unless @AndyEPhipps and @KrupaPammi have anything else to add?

2023-04-27 12:11 UTC, michael-odonovan commented
Have sorted out Button issue. Error message is in view.

2023-05-09 11:18 UTC, AndyEPhipps commented
> Tried to use setFocus() on the input after clicking the button, but something isn't working, so looks quite tricky to get that

I'll give this a look as part of the re-review, hold on your hat

2023-05-09 11:24 UTC, AndyEPhipps approved these changes
Good stuff, mate 👍

2023-05-09 11:26 UTC, AndyEPhipps requested changes
Although it looks like you've remove recent work with that master merge; can re-do this please

2023-05-09 12:54 UTC, merged